language: objective-c
osx_image: xcode9.4

script:
    - set -o pipefail
    - xcodebuild -workspace XCoordinator-Example/XCoordinator-Example.xcworkspace -scheme XCoordinator-Example -destination platform\=iOS\ Simulator,OS\=11.4,name\=iPhone\ X build | xcpretty