osx_image: xcode9.4
language: objective-c

script:
    - xcodebuild -workspace XCoordinator-Example/XCoordinator-Example.xcworkspace -scheme 'XCoordinator-Example' | xcpretty -c; exit ${PIPESTATUS[0]}