osx_image: xcode9.4
language: objective-c

script:
    - xctool -workspace XCoordinator-Example/XCoordinator-Example.xcworkspace -scheme 'XCoordinator-Example' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 